"""Unit tests for LLM provider selection and fallback chain:
DeepSeek / OpenAI -> NVIDIA (kimi-k3) -> Dedalus.
"""

import asyncio

import pytest

import agents.base as base


class TestProviderDetectionAndKeys:
    def test_detect_deepseek_when_configured(self, monkeypatch):
        monkeypatch.delenv("LLM_PROVIDER", raising=False)
        monkeypatch.setenv("DEEPSEEK_API_KEY", "deepseek-test-key")
        monkeypatch.setenv("OPENAI_API_KEY", "openai-test-key")
        assert base.get_provider() == "deepseek"

    def test_detect_nvidia_from_vite_key(self, monkeypatch):
        monkeypatch.delenv("OPENAI_API_KEY", raising=False)
        monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
        monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)
        monkeypatch.delenv("LLM_PROVIDER", raising=False)
        monkeypatch.setenv("VITE_NVD_API_KEY", "nvapi-test-key")
        monkeypatch.delenv("NVIDIA_API_KEY", raising=False)
        monkeypatch.delenv("NVD_API_KEY", raising=False)
        monkeypatch.delenv("DEDALUS_API_KEY", raising=False)

        assert base._get_nvidia_api_key() == "nvapi-test-key"
        assert base.get_provider() == "nvidia"
        assert base.get_model_name() == "moonshotai/kimi-k3"
    def test_explicit_nvidia_provider(self, monkeypatch):
        monkeypatch.setenv("LLM_PROVIDER", "nvidia")
        monkeypatch.setenv("NVIDIA_API_KEY", "nvapi-test-key")
        assert base.get_provider() == "nvidia"

    def test_fallback_chain_construction(self, monkeypatch):
        monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)
        monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
        monkeypatch.setenv("VITE_NVD_API_KEY", "nvapi-test")
        monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
        monkeypatch.delenv("DEDALUS_API_KEY", raising=False)

        chain = base._get_fallback_chain("openai")
        assert chain == ["openai", "nvidia"]

    def test_fallback_chain_construction_deepseek_primary(self, monkeypatch):
        monkeypatch.setenv("DEEPSEEK_API_KEY", "deepseek-test")
        monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
        monkeypatch.setenv("VITE_NVD_API_KEY", "nvapi-test")
        monkeypatch.delenv("AZURE_OPENAI_API_KEY", raising=False)
        monkeypatch.delenv("DEDALUS_API_KEY", raising=False)

        chain = base._get_fallback_chain("deepseek")
        assert chain == ["deepseek", "openai", "nvidia"]



class TestRuntimeFallback:
    def test_fallback_openai_to_nvidia(self, monkeypatch):
        monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)
        monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
        monkeypatch.setenv("VITE_NVD_API_KEY", "nvapi-test")
        monkeypatch.delenv("LLM_PROVIDER", raising=False)
        call_log = []

        async def fake_execute(provider, resolved_model, prompt, system_prompt, max_tokens, name, json_mode):
            call_log.append((provider, resolved_model))
            if provider == "openai":
                raise RuntimeError("OpenAI rate limited / 429")
            if provider == "nvidia":
                return "Generated by NVIDIA Kimi-k3"
            raise RuntimeError(f"Unexpected provider {provider}")

        monkeypatch.setattr(base, "_execute_provider_call", fake_execute)

        result = asyncio.run(base.call_llm("Generate Manim video code", model="gpt-4o"))
        assert result == "Generated by NVIDIA Kimi-k3"
        assert call_log == [
            ("openai", "gpt-4o"),
            ("nvidia", "moonshotai/kimi-k3"),
        ]

    def test_fallback_deepseek_to_openai_to_nvidia(self, monkeypatch):
        monkeypatch.setenv("DEEPSEEK_API_KEY", "deepseek-test")
        monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
        monkeypatch.setenv("VITE_NVD_API_KEY", "nvapi-test")
        monkeypatch.delenv("LLM_PROVIDER", raising=False)

        call_log = []

        async def fake_execute(provider, resolved_model, prompt, system_prompt, max_tokens, name, json_mode):
            call_log.append((provider, resolved_model))
            if provider == "deepseek":
                raise RuntimeError("DeepSeek 500 error")
            if provider == "openai":
                raise RuntimeError("OpenAI 429 Too Many Requests")
            if provider == "nvidia":
                return "Generated by NVIDIA Kimi-k3"
            raise RuntimeError(f"Unexpected provider {provider}")

        monkeypatch.setattr(base, "_execute_provider_call", fake_execute)

        result = asyncio.run(base.call_llm("Generate code", model="gpt-4o"))
        assert result == "Generated by NVIDIA Kimi-k3"
        assert [provider for provider, _ in call_log] == ["deepseek", "openai", "nvidia"]

    def test_fallback_all_fail_raises_last_error(self, monkeypatch):
        monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)
        monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
        monkeypatch.setenv("VITE_NVD_API_KEY", "nvapi-test")
        monkeypatch.delenv("LLM_PROVIDER", raising=False)

        async def fake_execute(provider, resolved_model, prompt, system_prompt, max_tokens, name, json_mode):
            raise RuntimeError(f"{provider} service down")

        monkeypatch.setattr(base, "_execute_provider_call", fake_execute)

        with pytest.raises(RuntimeError, match="nvidia service down"):
            asyncio.run(base.call_llm("Generate code"))

    def test_sync_fallback_openai_to_nvidia(self, monkeypatch):
        monkeypatch.delenv("DEEPSEEK_API_KEY", raising=False)
        monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
        monkeypatch.setenv("VITE_NVD_API_KEY", "nvapi-test")
        monkeypatch.delenv("LLM_PROVIDER", raising=False)

        call_log = []

        def fake_execute_sync(provider, resolved_model, prompt, system_prompt, max_tokens, name, json_mode):
            call_log.append((provider, resolved_model))
            if provider == "openai":
                raise RuntimeError("OpenAI connection failed")
            if provider == "nvidia":
                return "Sync response from NVIDIA"
            raise RuntimeError("Unexpected")

        monkeypatch.setattr(base, "_execute_provider_call_sync", fake_execute_sync)

        result = base.call_llm_sync("Prompt", model="gpt-4o")
        assert result == "Sync response from NVIDIA"
        assert call_log == [
            ("openai", "gpt-4o"),
            ("nvidia", "moonshotai/kimi-k3"),
        ]
